version: "3.9"

services:
  apartment_api:
    build:
      context: ./apartment_api
    container_name: apartment_api
    ports:
      - "8000:8000"
    volumes:
      - ./apartment_api/app/database:/app/database
    networks:
      - api_network
    command: >
      sh -c "
      sleep 15 &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  booking_api:
    build:
      context: ./booking_api
    container_name: booking_api
    ports:
      - "8001:8001"
    volumes:
      - ./booking_api/app/database:/app/database
    networks:
      - api_network
    command: >
      sh -c "
      sleep 15 &&
      uvicorn main:app --host 0.0.0.0 --port 8001 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://apartment_api:8000"]
      interval: 10s
      timeout: 5s
      retries: 3


  search_api:
    build:
      context: ./search_api
    container_name: search_api
    ports:
      - "8002:8002"
    volumes:
      - ./search_api/app/database:/app/database
    networks:
      - api_network
    command: >
      sh -c "
      sleep 15 &&
      uvicorn main:app --host 0.0.0.0 --port 8002 --reload
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://apartment_api:8000 || exit 1 && curl -f http://booking_api:8001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3


  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8003:8003"
    networks:
      - api_network
    command: >
      sh -c "
      sleep 15 &&
      uvicorn main:app --host 0.0.0.0 --port 8003 --reload
      "

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Broker port
      - "40672:40672"  # Management UI
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
