version: "3.9"

services:
  apartment_api:
    build:
      context: ./apartment_api
    container_name: apartment_api
    ports:
      - "8000:8000"
    volumes:
      - ./apartment_api/app/database:/app/database
    networks:
      - api_network
    command: 
      " uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test:  "curl -f http://localhost:8000/health"
      interval: 30s
      timeout: 5s
      retries: 3

  booking_api:
    build:
      context: ./booking_api
    container_name: booking_api
    ports:
      - "8001:8001"
    volumes:
      - ./booking_api/app/database:/app/database
    networks:
      - api_network
    command: 
      "uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    depends_on:
      apartment_api:
        condition: service_healthy
    healthcheck:
      test:  "curl -f http://localhost:8001/health"
      interval: 30s
      timeout: 5s
      retries: 3


  search_api:
    build:
      context: ./search_api
    container_name: search_api
    ports:
      - "8002:8002"
    volumes:
      - ./search_api/app/database:/app/database
    networks:
      - api_network
    command:
      "uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    depends_on:
     booking_api:
        condition: service_healthy 
    healthcheck:
      test:  "curl -f http://localhost:8002/health"
      interval: 30s
      timeout: 5s
      retries: 3

      
  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8003:8003"
    networks:
      - api_network
    command: 
      "uvicorn main:app --host 0.0.0.0 --port 8003 --reload"
    depends_on:
     search_api:
        condition: service_healthy
    healthcheck:
      test:  "curl -f http://localhost:8003/health"
      interval: 30s
      timeout: 5s
      retries: 3
      

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Broker port
      - "15672:15672"  # Management UI
    networks:
      - api_network
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  api_network:
    driver: bridge
